### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by AeromeFileManager** [DevER-M/yami#6]
I had some issues installing Yami that prevented me from immediately using it when installing via ```pip install```.

- The first was:
```
$ yami
Traceback (most recent call last):
  File "/home/linuser/.local/bin/yami", line 5, in <module>
    from yami.main import entry
  File "/home/linuser/.local/lib/python3.10/site-packages/yami/__init__.py", line 1, in <module>
    from .music import MusicPlayer
  File "/home/linuser/.local/lib/python3.10/site-packages/yami/music.py", line 4, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```
which I managed to fix by installing python3-tk via ```sudo apt install python3-tk``` on my Ubuntu install.

- The second was an error with missing files:
```
Traceback (most recent call last):
  File "/home/linuser/.local/bin/yami", line 5, in <module>
    from yami.main import entry
  File "/home/linuser/.local/lib/python3.10/site-packages/yami/__init__.py", line 1, in <module>
    from .music import MusicPlayer
  File "/home/linuser/.local/lib/python3.10/site-packages/yami/music.py", line 24, in <module>
    ctk.set_default_color_theme("data/theme.json")
  File "/home/linuser/.local/lib/python3.10/site-packages/customtkinter/__init__.py", line 69, in set_default_color_theme
    ThemeManager.load_theme(color_string)
  File "/home/linuser/.local/lib/python3.10/site-packages/customtkinter/windows/widgets/theme/theme_manager.py", line 23, in load_theme
    with open(theme_name_or_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/theme.json'
```

I managed to fix that one by cloning your git repository and copying the "data" and ".assets" folders into my current working directory before launching yami. This is obviously a temporary fix though. This issue stems from the fact that you used a relative import in music.py on line 24:

```ctk.set_default_color_theme("data/theme.json")```

The "install from source" method works though because you have people set up a virtual environment via venv when installing, I think.

After that the software works great! Congrats on getting it released.

**Comment by DevER-M** [comment]
i will fix this asap

**Comment by johnblommers** [comment]
I get the same error:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/theme.json'`

**Comment by rbreaves** [comment]
Does not work on macOS, the pip based install is broken same way as mentioned above. Git cloning and installing gets further but also borks at this point. Guessing this was only tested on Windows &/or Linux.

Imo - it may be better to recreate this app as a web based app so that you just run a web server and from there you know your UI would load fine - plus it could then more than likely run on iOS (iSH) and Android (Termux) or via something like Cordova.

```
pygame 2.6.1 (SDL 2.28.4, Python 3.12.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Fatal Python error: PyEval_RestoreThread: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Thread 0x000000016ec63000 (most recent call first):
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 359 in wait
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 655 in wait
  File "/Users/rreaves/.local/lib/python3.12/site-packages/rich/live.py", line 29 in run
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1075 in _bootstrap_inner
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1032 in _bootstrap

Current thread 0x00000001d7f01c40 (most recent call first):
  File "/Users/rreaves/.local/lib/python3.12/site-packages/yami/music.py", line 233 in initialize_pygame
  File "/Users/rreaves/.local/lib/python3.12/site-packages/yami/music.py", line 58 in __init__
  File "/Users/rreaves/.local/lib/python3.12/site-packages/yami/main.py", line 10 in entry
  File "/Users/rreaves/.local/bin/yami", line 8 in <module>

Extension modules: objc._objc, CoreFoundation._CoreFoundation, CoreFoundation._inlines, Foundation._Foundation, Foundation._inlines, AppKit._AppKit, AppKit._inlines, PIL._imaging, _brotli, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, rapidfuzz.distance._initialize_cpp, rapidfuzz.distance.metrics_cpp, rapidfuzz.fuzz_cpp, rapidfuzz.process_cpp_impl, rapidfuzz.utils_cpp, lxml._elementpath, lxml.etree, pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, PIL._imagingmath, PIL._imagingtk (total: 58)
[1]    3187 abort      yami
```

**Comment by DevER-M** [comment]
woah i tested this project only on linux with wayland
if possible contribute to the project thanks 😉
