### ISSUE TITLE
No such file or directory: 'yami/data/theme.json'

### ISSUE THREAD

**Issue by morellik** [DevER-M/yami#9]
After the pip installation, I try to execute yami but I receive the following exception:

pygame 2.6.1 (SDL 2.28.4, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/morelli/.local/bin/yami", line 5, in <module>
    from yami.main import entry
  File "/home/morelli/.local/lib/python3.9/site-packages/yami/__init__.py", line 1, in <module>
    from .music import MusicPlayer
  File "/home/morelli/.local/lib/python3.9/site-packages/yami/music.py", line 24, in <module>
    ctk.set_default_color_theme("yami/data/theme.json")
  File "/home/morelli/.local/lib/python3.9/site-packages/customtkinter/__init__.py", line 69, in set_default_color_theme
    ThemeManager.load_theme(color_string)
  File "/home/morelli/.local/lib/python3.9/site-packages/customtkinter/windows/widgets/theme/theme_manager.py", line 23, in load_theme
    with open(theme_name_or_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'yami/data/theme.json'

**Comment by DevER-M** [comment]
ill look into the problem

**Comment by Hello2k2** [comment]
Hi @DevER-M,Your music player project is awesome! I really like it.Could I fork this project to explore it and maybe try contributing some ideas?Thanks!
